### ISSUE TITLE
Feature with self-intersections won't render properly

### ISSUE THREAD

**Issue by cedricr** [neocarto/bertin#108]
I'm trying to render topojsons downloaded via the [Cartiflette](https://github.com/InseeFrLab/cartiflette) library.

Some of them (here, Normandy) won't render properly with Bertin.js.
![image](https://user-images.githubusercontent.com/7826756/219958473-77e1f63b-af13-4770-9571-d9ebfd08e2a3.png)

Once simplified via topojson.simplify, they do render as expected.
![image](https://user-images.githubusercontent.com/7826756/219958482-f4de0fc7-0946-4efc-8886-c3ee0a98323f.png)

Plot will also display them as expected:
![image](https://user-images.githubusercontent.com/7826756/219958505-5258368b-aa16-4dcb-96fa-b8ab86dc9fbe.png)

QGIS reports some of the features as having self-intersections, which I guess is what causes the problem in Bertin, but as it's a rather common defect, it would be nice if Bertin could manage to display them anyway.

Minimal repro here: https://observablehq.com/d/01779a4ad998a10b

More examples can be found in this notebook: https://observablehq.com/d/673577af814d80cd

**Comment by TomBor** [comment]
A passage through [rewind](https://observablehq.com/@fil/rewind) by @Fil can do the trick.
Maybe Plot.geo do it by default.

**Comment by mthh** [comment]
Indeed, rewind can do the trick, and I think this is also in the works for Bertin as a rewind function has been added to [neocarto/geotoolbox](https://github.com/neocarto/geotoolbox) very recently :+1:

**Comment by Fil** [comment]
Plot does not apply rewind by default. It only works in your Plot example because you've made the projection to fit the _mesh_.

**Comment by cedricr** [comment]
@Fil oh I see ! I still think it would be nice for Bertin to do it by default, as it's not the first time I encounter the problem, but let's see what @neocarto says.

**Comment by Fil** [comment]
Two arguments against:
1. it's a bit slower than fixing the problem in the geojson, so you don't want to run it by default
2. some geojson shapes are legitimately "larger than a hemisphere" (the typical example being the [ocean](https://observablehq.com/@fil/ocean))

**Comment by mthh** [comment]
@Fil I don't want to hijack this discussion thread (as the answer I'm looking for is probably in one of your explanations in a notebook or in a d3-geo issue), but is it necessarily a problem to apply rewind to polygons larger than the hemisphere? 

In Magrit we apply rewind by default and we have no problem to display the ocean layer of the notebook you linked.

**Comment by cedricr** [comment]
I did the test just to be sure, and rewind does fix the problem: https://observablehq.com/d/e387c527b779b40c

> it's a bit slower than fixing the problem in the geojson

I'll try to find the exact source of the problem in this case (the geojson comes from AdminExpress Carto, but by loading directly the source shape file, I don't see self-intersection errors in QGIS, I've got to check what other transformations are done. (cc: @linogaliana))

But the point is, those files do exist, and it's a bit disapointing when you are trying to display them and they just don't render properly, and people won't know what they have to do to make them work.
Maybe a boolean flag would do the job -- Bertin already has 'clip', for a similar issue.

**Comment by Fil** [comment]
@mthh try with with this one: https://observablehq.com/@fil/ocean/2

Magrit shows the _land_ in grey instead of the ocean.

**Comment by mthh** [comment]
@Fil I'm still seeing the ocean being colored and the land being representend as hole (as expected)

![export(1)](https://user-images.githubusercontent.com/12172162/220155216-42648606-481a-4587-b8f7-7c184396e64f.png)

**Comment by Fil** [comment]
I've tried again and it's not what I get :)

open https://magrit.cnrs.fr/ > new project > add a basemap > layout layer "ocean.json" > wait two minutes > "Layer successfully added to the map" > the land is gray. And when I click on "feature information" the cursor on land shows me "ocean_1".

**Comment by mthh** [comment]
My bad, I was still using the "ocean.json" from your first notebook.

**Comment by Fil** [comment]
Note that [@fil/rewind](https://observablehq.com/@fil/rewind) is "smarter" than [mapbox/geojson-rewind](https://github.com/mapbox/geojson-rewind), in the sense that if there is a polygon with hole, it checks if the outer ring contains the first point of the hole, and doesn't invert the polygon. So this second ocean.json file would not break. (The only case where it can not decided is a single ring polygon.)

**Comment by mthh** [comment]
Alright, thanks a lot for explaining the difference between the two !
I'll open an issue on Magrit repository and see how I'll handle it there.

**Comment by neocarto** [comment]
I'm on vacation, thanks for this feedback and discussion. Indeed, I had the intention to improve the imports of geojson with notably the rewind fonction from mapbox. Cf this notebook. https://observablehq.com/d/660137cff3c11502
Maybe we can work together for Bertin and Magrit ? With fil's rewind ?

**Comment by neocarto** [comment]
I'm on vacation, thanks for this feedback and discussion. Indeed, I had the intention to improve the imports of geojson with notably the rewind fonction from mapbox. Cf this notebook. https://observablehq.com/d/660137cff3c11502
Maybe we can work together for Bertin and Magrit ? With fil's rewind ?

**Comment by neocarto** [comment]
A solution is proposed in bertin@1.6.5. In each layer, we can use rewind = true. See https://vis.social/@neocarto/110027972115777708
