### ISSUE TITLE
DOM is (unnecessarily) updated when moving cursor over the map 

### ISSUE THREAD

**Issue by mthh** [neocarto/bertin#112]
When moving the cursor over some map made with Bertin, the DOM is sometimes unnecessarily (according to my understanding) updated.

See the video I attached on which I'm simply moving the cursor: 

https://user-images.githubusercontent.com/12172162/234621581-a61edb48-f60d-4d68-b582-06d472fc0f98.mp4

While glancing at the code, it seems that, in the 'mousemove' event handler, you are calling `raise` on the hovered entities only if there is a toopltip, however on the 'mouseleave' event handler you are calling `lower` (https://github.com/neocarto/bertin/blob/main/src/layers/simple.js#L236) whether there is a tooltip or not.

**Comment by neocarto** [comment]
Solved
