### ISSUE TITLE
use d3.symbol instead of svg <circle> or <rect>

### ISSUE THREAD

**Issue by TomBor** [neocarto/bertin#12]
Would it be simpler to use [d3.symbol](https://github.com/d3/d3-shape#symbols) for all points geometries: simple layer or prop layer?

The logic is different but similar for all symbol type (circle, square, triangle, cross).
All shape are render with path and move to position with transform + translate.

**Comment by neocarto** [comment]
Good idea. The implementation fo simple layers is done. See: https://observablehq.com/@neocartocnrs/bertin-js-symbols?collection=@neocartocnrs/bertin

**Comment by neocarto** [comment]
https://observablehq.com/@neocartocnrs/bertin-js-symbols?collection=@neocartocnrs/bertin
