### ISSUE TITLE
[bertin-js links] filtering links options

### ISSUE THREAD

**Issue by fbahoken** [neocarto/bertin#15]
in : https://observablehq.com/@neocartocnrs/bertin-js-links

Please, for these first examples, allow also filtering links from their volum (flow value).

Then, it would be interesting to propose to filter according to (by order of importance/difficulty) :

Type (1)
- a value to enter
- the mean value of (fij)
- median value of (fij)

Type (2)
- a decile of of (fij) to be entered or calculated (?). 
-This proposition is related to the summary proposal issue.

Type (3)
- a range of values to enter 
- a range a value to pick on a sort of slider histogram

Type (4)
- a range of values to enter as from [a - b[
- a range a value to pick on a "slider histogram"

**Comment by neocarto** [comment]
Filters are done outside bertinjs. Another package to build ?

**Comment by fbahoken** [comment]
> ok for the flow filters to be made outside bertinjs.
and ok to make another package, let's plan to talk about it ...
