### ISSUE TITLE
color options for links

### ISSUE THREAD

**Issue by fbahoken** [neocarto/bertin#16]
Please add the possibility to sampling the color of links/arrows in CMJN (or other), by default in RGB. 

If possible, propose to :
- choose the color 
- sampling/selecting the alpha parameter of the color (opacity)
- sampling of the color in relation to the sampling of the flow values (direct or inverse function). i.e. allow to display +/- dark links/arrows according to whether they are strong or weak (as desired) - and the possibility of combining the hue with the opacity parameter

**Comment by neocarto** [comment]
Up to now, we can use choro or typo parameters for all layers.
