### ISSUE TITLE
summary of stats series

### ISSUE THREAD

**Issue by fbahoken** [neocarto/bertin#17]
Propose if it is possible the possibility to ***visualize the histogram*** of distribution of the statistical series
- useful for stats breaks/discretization : choosing of class parameter
- useful for links : choosing the filtering parameter of links/arrows values

This is in connection with the **display/calculation of a summary** of the series (or the sub-series) to be represented.

Perhaps propose an **interactive histogram**? 
or on which we could also set the bounds?

It can be discussed according to the possibilities

**Comment by neocarto** [comment]
Not in bertin.js. I suggest to add new features in statsbreks.
