### ISSUE TITLE
Tooltips doesn’t work in Firefox 97.0.1 on macos.

### ISSUE THREAD

**Issue by neocarto** [neocarto/bertin#18]
Tooltips  doesn’t work in Firefox 97.0.1 on macos.
See https://talk.observablehq.com/t/tooltips-in-bertin-js/6278/7

**Comment by arky** [comment]
Tooltips work on both Firefox 99 (aurora) and Firefox 97 (mainline) on gnu/Linux gnome-shell. 
![image](https://user-images.githubusercontent.com/808895/159158075-0fdd221f-3fd8-462a-8a25-fc74a22b05d0.png)
