### ISSUE TITLE
Tooltip performance

### ISSUE THREAD

**Issue by ericemc3** [neocarto/bertin#21]
Tooltips dont follow smoothly mouse move on maps with more than 1,000 items.
=> https://observablehq.com/@ericmauviere/hello_bertin1

I suspect `raise()/lower()` on `mousemove/mouseleave` to be responsible.

**Comment by arky** [comment]
Attaching performance profile from Firefox DevTools for analysis. 
[bertin-perfomance.zip](https://github.com/neocarto/bertin/files/8311013/bertin-perfomance.zip)
