### ISSUE TITLE
module import in Quarto

### ISSUE THREAD

**Issue by neocarto** [neocarto/bertin#30]
Currently, require("bertin") does'nt work in [Quarto](https://quarto.org/docs/tools/rstudio.html). The following error is returned: OJS Error. RequireError$1: invalid module. To import bertin, I have to write: *bertin = import('https://cdn.skypack.dev/bertin@0.9')*.  However, require works in Observable. It's weird... See also https://talk.observablehq.com/t/quarto-module-require/6573 & https://stackoverflow.com/questions/72300480/error-quarto-require-invalid-module-bertin-js
![Screenshot from 2022-05-19 10-53-08](https://user-images.githubusercontent.com/8111373/169255582-89229d01-5093-4f88-93f4-895111c75133.png)
Actually, it's very weird. There is an error in rstudio. But when I deploy the page in github ([see](https://neocarto.github.io/Quarto/ojs_require.html)), the error disappears.

**Comment by cscheid** [comment]
(Quarto dev here) [This commit](https://github.com/quarto-dev/quarto-cli/commit/97b69958010cc5321b2e8d688d189b2a7d52d9f0) from yesterday addresses a bug in our version of d3-require (which we need for interoperability with imports from ipython's html widgets). Could you upgrade to the latest quarto version and test that? Thanks!

**Comment by neocarto** [comment]
The problem is not solved with quarto 0.9.434 :(

**Comment by cscheid** [comment]
Huh, weird. This is what it looks like for me locally:

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/285675/169549320-357d9db0-5c95-4062-964b-6c16d1e0161b.png">

**Comment by neocarto** [comment]
Within Rstudio : 
- It works if I choose "Preview in window". Output in localhost is ok.
- It doesn't work if I choose "Preview in Viewer Pane". Cf screenshot above.

**Comment by neocarto** [comment]
Solved : https://github.com/quarto-dev/quarto-cli/issues/943
