### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by neocarto** [neocarto/bertin#31]
Update the documentation (=> bertin@1.0)

**Comment by arky** [comment]
@neocarto I think it is better to update the documentation in the main readme file first before expanding the observable examples. Thoughts?

**Comment by neocarto** [comment]
Agree with that. My goal is to fix some bugs bugs, update the doc and release a 1.0 version. Then, add new features.

**Comment by arky** [comment]
@neocarto Perhaps adding Changelog file might be a good idea to track these changes ?

**Comment by arky** [comment]
@neocarto Am working on improving the usability and readability of documentation. Do you have a timeline for 1.0 release?

**Comment by neocarto** [comment]
I have some tests to do. But I think my answer will be: asap 🤷‍♂️

**Comment by arky** [comment]
Great @neocarto 

Am rewriting the docs using the same language and design of all plot docs. So it reads natural and feel familiar to anyone who are familiar with plot docs.
