### ISSUE TITLE
locale number in tooltip

### ISSUE THREAD

**Issue by TomBor** [neocarto/bertin#43]
With [Number.prototype.toLocaleString()](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString), tooltip could render more readable number.
By default, it could be the browser locale, with an option to choose a specific one. A more refined option could be the optional object of `toLocaleString()` who have useful properties.

**Comment by neocarto** [comment]
Good idea.
