### ISSUE TITLE
add id or class attribute to layer

### ISSUE THREAD

**Issue by TomBor** [neocarto/bertin#46]
### Ideas
+ being able to style a map outside of bertin.js with a simple style sheet in css
+ apply the same style to several maps generated with bertin.js
+ reduce bertin.js to its logical part or in other word dissociate styling from things related to data

### How
+ improve structure of the generated svg :
   + each layer must be in a level 1 group and must have an id attribute
   + element inside a layer could have a class attribute (`.bubble` for bubbles layer...)

**Comment by jeandav** [comment]
Hello. I am facing this issue as well. Did you manage to find a way around it?
