### ISSUE TITLE
Pan and zoom to layer

### ISSUE THREAD

**Issue by rysebaert** [neocarto/bertin#50]
Pan and zoom to specific area of the layer, following the idea behind [this implementation](https://observablehq.com/@d3/zoom-to-bounding-box?collection=@d3/d3-zoom).

Proposal : no impact on the layout (leg_x, leg_y, text title_pos, type: "text" parameters) in the canevas, no impact on bubble sizes ; only on Scalebar values.

**Comment by neocarto** [comment]
I'm not sure it's relevant at this stage. Anyway, not before the release 1.0. So, I close this issue and open a discussion on this topic.
