### ISSUE TITLE
Add leg_top parameter for the legend

### ISSUE THREAD

**Issue by rysebaert** [neocarto/bertin#52]
if leg_top = TRUE (default value), then the legend is displayed on top of the map. To avoid overlapping with layers used for the map layout.

**Comment by neocarto** [comment]
Ok. Thank you for the feed back. One solution might be to use the svg <use> element. To be tested...
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use
Another solution would be to export the legend functions and make them accessible outside the cartographic representation function.

**Comment by neocarto** [comment]
Fixed: See https://github.com/neocarto/bertin/commit/4874ef9cab1eb525497a6b2a0ba4a833aa38ffc9
just use require("bertin@0.9.18") and run your code.
