### ISSUE TITLE
Set color mapping manually for Typology

### ISSUE THREAD

**Issue by vorbei** [neocarto/bertin#58]
In a typical scenario using 'typo' layer,

```
bertin.draw({
layers: [
  {
    type: "layer",
    geojson: data,
    fill: {
      type: "typo",
      values: "region",
      pal: "Tableau10",
      tooltip: ["$region", "$name"],
      leg_title: `The Continents`,
      leg_x: 55,
      leg_y: 180
    }
  ]
})
```

It's possible to manually set the palette, but the order and the color mapping is not configurable.
Using d3 or vega-lite, it's done with the color scale domain and range setting. 

In bertin's 'typo' example, the continent is colorized fine. However, the order of the continents is not totally in control.(Africa, Oceania, Asia,...) It's possible the order is arranged silently by the features. For a press-ready scenario, the names should be Africa, America, Asia, Europe, Oceania... etc, or any desired order. 

For some other cases, like risks (Low, Mid, High), it's another typical typology, but if the order is not in control, the color is randomized, the outcomes is not usable.

Please consider this issue. Thanks.

**Comment by neocarto** [comment]
Thank you for your suggestion.

I will add a parameter "order" to set the order of the values in the next patch. 

Then, if I have : 

values: "region",
pal: ["red","green", "blue"],
order:["Africa", "Asia", "Australia"]

Africa will be in red, Asia in green and Australie in blue.

Regards.
N.
