### ISSUE TITLE
suggestion to use camelCase

### ISSUE THREAD

**Issue by Fil** [neocarto/bertin#6]
I would suggest to change all css property names (strokewidth, fillopacity) etc to camelCase, because it is [what javascript uses](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents) to manipulate css values. Happy to provide the pull-request if you like.

**Comment by neocarto** [comment]
Ok Fil, it sounds good. If you have tile to provide a pull-request, it would be great. Let me know when you plan to work on it.
