### ISSUE TITLE
User configurable tile styles / url templates

### ISSUE THREAD

**Issue by vorbei** [neocarto/bertin#60]
in https://github.com/neocarto/bertin/blob/main/src/layers/tiles.js
the 'style' parameter only supports string type, and not user extendable.

for a custom style/url, please consider support Object parameter like
 ```
{
      name: "openstreetmap",
      provider: "OpenStreetMap contributors",
      url: (x, y, z) => `https://tile.openstreetmap.org/${z}/${x}/${y}.png`,
    },
````

**Comment by neocarto** [comment]
Thank you for this PR. It is available in bertin@1.0.6.
I have removed the "name" property which is useless in this case. 
Thank you again :-)
