### ISSUE TITLE
Labels don't work on Point layer

### ISSUE THREAD

**Issue by cedricr** [neocarto/bertin#63]
Example notebook: https://observablehq.com/d/5d8fbd0cdf8084bc

On this map, the "pointLabels" geojson won't render as a "label" layer with the following error:
`fr = TypeError: coordinates must be finite numbers`

Removing the lambert93 projection will get rid of the error, but the labels are all displayed at coordinates (0,0).

The same geojson will render correctly after buffering with Turf (in order to get polygonal geoms).

**Comment by neocarto** [comment]
Solved in patch 1.0.1 => use  require("bertin@1.0.1)
