### ISSUE TITLE
Rendering of USA map using geoAlbersUsa not as expected.

### ISSUE THREAD

**Issue by gallowayevan** [neocarto/bertin#65]
I've really enjoyed playing with this library - fills a much needed gap in javascript cartography!

I ran into an issue making a map of the US. I have geojson of US states from the US Census (https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html; converted from shapefile to geojson using mapshaper). When I try to make a state map using bertin.js, I get this: https://observablehq.com/d/c5d2bf78b1e0534e
The most interesting thing about the rendering is that one state at a time will be stroked white, and you can trigger a change in the displayed state by mousing out of the cell.

I'm not sure what is causing this - maybe the Alaska and Hawaii inset in the AlbersUSA projection break things somehow?

**Comment by Fil** [comment]
The shapes are not in the winding order that D3 expects; try this import:
`import {normalizeWindingInPlace} from "@fil/normalize-winding"`

then call
`cb_2021_us_state_500k = FileAttachment("cb_2021_us_state_500k.json").json().then(normalizeWindingInPlace)`

**Comment by gallowayevan** [comment]
Thanks, Fil! That was it. I thought I had checked the winding order when converting in mapshaper, but I guess not!
