### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by saneef** [neocarto/bertin#80]
When I run `npm run build`, I'm getting error: 

```sh
[!] (plugin copy) Error: EACCES: permission denied, mkdir '/var/www'
```

It looks like it is caused by the path set on [this line of `rollup.config.js`](https://github.com/neocarto/bertin/blob/d496c85ad088bd184689161585f0795b546b61b0/rollup.config.js#L24), which is not there in my system.

**Comment by neocarto** [comment]
Ok. I use this for my tests. What do you suggest?

**Comment by saneef** [comment]
Ideally don't write anything outside of the project directory. If you need to retain the path `/var/www/html/npm_test/bertin/index.min.js` for you local serving or test, does a soft link from than folder to the built file within the project work?

**Comment by neocarto** [comment]
Okay, I get it. I'll remove that in the next patch. 
It's effectively useless. I can do otherwise.
Thanks for your advice.
