### ISSUE TITLE
Dorling with labels, 1.4.0 = contourDensity error

### ISSUE THREAD

**Issue by lessthanweb** [neocarto/bertin#83]
Hi,

Is there any way one could add labels to the dorling bubbles? The labels are shown but they are shown over the countries not bubbles.

Also, tried using the latest version and I get contourDensity not defined error.. Have loaded the https://cdn.jsdelivr.net/npm/d3-contour@4 but not working. What's the trick here?

Thanks.

**Comment by neocarto** [comment]
Labels are not associated to dorling bubbles yet. But I'm thinking about it. Maybe in a future release.
I don't understand the second point.
