### ISSUE TITLE
Missing bracket in the readme

### ISSUE THREAD

**Issue by terezaif** [neocarto/bertin#84]
heya, when copy-pasting the code, it didn't work, a closing } is missing before the ]

<img width="996" alt="Screenshot 2022-11-19 at 20 24 21" src="https://user-images.githubusercontent.com/6162692/202867979-fffd1ad7-a6d2-4540-bb02-d81cfd1da716.png">

**Comment by neocarto** [comment]
Thanks! In addition, your feedbacks and contributions on `bertin` are welcome.
