### ISSUE TITLE
Line Marker Styles 

### ISSUE THREAD

**Issue by arky** [neocarto/bertin#85]
Allow customization of line marker styles.  Perhaps line markers could have user defined solid, long, short, or dashes. 

A example can be seen on flourish https://help.flourish.studio/article/287-how-to-add-lines-to-your-map
![image](https://user-images.githubusercontent.com/808895/203288994-e8aae761-7ef8-4bc0-8584-c21a1d19bc7f.png)

Currently Bertin.js support line styles using 'Links'. These are fairly automatic. 

The use case for line markers are used for creating maps that show travel paths as seen [here](https://commons.wikimedia.org/wiki/File:Travel_Route_of_Ibn_Battuta_from_Delhi_to_Beijing_%28Ko%29.svg)

![image](https://user-images.githubusercontent.com/808895/203289858-1444c867-b969-4840-8e91-6ac228abbe1f.png)

**Comment by neocarto** [comment]
I put it on my todo list: https://github.com/neocarto/bertin/blob/main/TODO.md

**Comment by arky** [comment]
Awesome! @neocarto
