### ISSUE TITLE
More styling for header type

### ISSUE THREAD

**Issue by zachperiscopic** [neocarto/bertin#93]
Would it be possible to allow for more styling options for the [header type](https://github.com/neocarto/bertin#header), like there are for the [text type](https://github.com/neocarto/bertin#texts)? Stuff like `fontFamily` and `fontWeight` spring to mind.

Really loving this work, fantastic job! Thanks.

**Comment by neocarto** [comment]
You are right. It's on my todo list. https://github.com/neocarto/bertin/blob/main/TODO.md

**Comment by zachperiscopic** [comment]
Great to see, thanks!
