### ISSUE TITLE
Cheatsheets image have artifacts

### ISSUE THREAD

**Issue by arky** [neocarto/bertin#99]
The cheatsheet maps image consist of numerous data point that lie outside the maps. 

Please see the  testcase and attached screenshot: https://observablehq.com/d/4e012db9a1e53bb6
![test-case](https://user-images.githubusercontent.com/808895/206468197-2b778aac-5756-4048-9093-72033d8faac2.png)

**Comment by neocarto** [comment]
Solved in bertin@1.6.3 #0366bb8 & #53a3bdf
